.TH apport\-retrace 1 "September 09, 2006" "Martin Pitt"

.SH NAME

apport\-retrace \- regenerate a crash report's stack trace

.SH SYNOPSIS

.B apport\-retrace
[
.I OPTIONS
]
.I report

.SH DESCRIPTION

.B apport-retrace
regenerates the stack traces (both the simple and the threaded one) in
an apport crash report from the included core dump. This requires the
affected package to be installed, of course, and the installed version
has to exactly match the version from the crash report.

This is particularly useful if debug symbols were not available at the
time of the report generation, which is the common case. After 
installing all the debug symbols, the regenerated stack trace will
be fully symbolic and thus become much more useful for developers to
fix the problem.

.SH OPTIONS

.TP
.B \-c, \-\-remove\-core
Remove the core dump from the report after stack trace regeneration.
By default it is retained.

.TP
.B \-g, \-\-gdb
Start an interactive gdb session with the report's core dump.

.TP
.B \-s, \-\-stdout
Write the new stack traces to stdout instead of putting them back into
the report.

.TP
.B \-o \fIFILE\fR, \fB\-\-output=\fIFILE
Write modified report to given file instead of changing the original
report.

.TP
.B \-d, \-\-download\-debug
Use apt to automatically download missing debug symbol packages
(.ddebs) and use them for creating a better stack trace. Please note
that this does not actually install these ddebs, thus no special
privileges are required. However, your
.B /etc/apt/sources.list
must contain an appropriate apt source for this to work.

.TP
.B \-C, \-\-cache\-dir \fIDIRECTORY
If using option 
.B\-\-download\-debug
to download ddebs, use the given directory as package cache. If not
given, a temporary directory is used.

.SH AUTHOR
.B apport
and the accompanying tools are developed by Martin Pitt
<martin.pitt@ubuntu.com>.
