.TH apport\-retrace 1 "September 09, 2006" "Martin Pitt"

.SH NAME

apport\-retrace \- regenerate a crash report's stack trace

.SH SYNOPSIS

.B apport\-retrace
[
.I OPTIONS
]
.I report

.SH DESCRIPTION

.B apport\-retrace
regenerates the stack traces (both the simple and the threaded one) in
an apport crash report from the included core dump. For this it
figures out the set of necessary packages and their accompanying debug
symbol packages (\fIpackage\fB\-dbgsym\fR), so that the regenerated
stack trace will be fully symbolic and thus become much more useful
for developers to fix the problem.

.B apport\-retrace 
attempts to install the missing packages with apt. This requires root
privileges, but will work fine in a chroot with the
.B fakeroot
and
.B fakechroot
tools, so that the entire process can be performed with just normal
user privileges.

If this tool is run as normal user, then it will merely print out the
missing packages as a warning and continue the retracing process. It
will yield worse up to unusable results, though.

.I report
is either the path to a .crash file, or a Launchpad bug number. In the
latter case, the information is downloaded from the bug report, and
you cannot change the report 'in\-place'; instead, you have to use one
of the options
.B \-g\fR,
.B \-s\fR, or
.B \-o\fR.

.SH OPTIONS

.TP
.B \-c, \-\-remove\-core
Remove the core dump from the report after stack trace regeneration.
By default it is retained.

.TP
.B \-g, \-\-gdb
Start an interactive gdb session with the report's core dump.

.TP
.B \-s, \-\-stdout
Write the new stack traces to stdout instead of putting them back into
the report.

.TP
.B \-o \fIFILE\fR, \fB\-\-output=\fIFILE
Write modified report to given file instead of changing the original
report.

.TP
.B \-v, \-\-verbose
Report download/install progress when installing additional packages.

.TP
.B \-u, \-\-unpack\-only
Only unpack the additionally required packages, do not configure them.
This is particularly useful when running this program with fakechroot,
when not every package can be cleanly installed completely.

.TP
.B \-h, \-\-help
Print a short online help that documents all options.

.SH AUTHOR
.B apport
and the accompanying tools are developed by Martin Pitt
<martin.pitt@ubuntu.com>.
