#!/bin/sh

set -e

mydir=$(dirname $0)
srcdir=$mydir/..

# XXX - this is a mess -mdz
# This only works if /usr/share/apport/java_uncaught_exception is installed
# It also dumps crash reports in /var/crash
# ...and doesn't even check if it worked!

# Should produce a crash report for $srcdir/java/crash.class
java -classpath $srcdir/java/apport.jar:$srcdir/java crash || true

# Should produce a crash report for $srcdir/java/crash.jar
java -classpath $srcdir/java/apport.jar:$srcdir/java/crash.jar crash || true
