#!/bin/sh
# Run all Apport self tests.
# Call without arguments to test the system instance, or with "local" to test
# the sources in the local tree.

# Copyright (C) 2007 - 2012 Canonical Ltd.
# Author: Martin Pitt <martin.pitt@ubuntu.com>
# 
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See http://www.gnu.org/copyleft/gpl.html for
# the full text of the license.

set -e

mydir=`dirname "$0"`

if [ "$1" = local ]; then
    export PATH=./bin:$PATH
    export PYTHONPATH=.
    export APPORT_CRASHDB_CONF=./etc/apport/crashdb.conf
    export APPORT_DATA_DIR=./data
    export APPORT_TEST_LOCAL=1

    if [ ! -e apport/packaging_impl.py ]; then
	echo "You need to copy an appropriate packaging implementation from backends/ to apport/packaging_impl.py; run './setup.py build' for auto-detection." >&2
	exit 1
    fi
fi

xvfb=
if type xvfb-run >/dev/null; then
    xvfb=xvfb-run
fi

failed=0

for t in $mydir/test_*.py; do
    echo "--- Testing $t ---"
    if [ "${t#*_ui_}" != $t ]; then
        prefix=$xvfb
    else
        # ensure that non-UI modules do not require X
        prefix="env -u DISPLAY"
    fi
    $prefix ${PYTHON:=python} -tt $t -v || failed=$((failed+1))
done

exit $failed
