.TH ubuntu\-bug 1 "February 15, 2007" "Martin Pitt"

.SH NAME

ubuntu\-bug \- file a bug against an Ubuntu package

.SH SYNOPSIS

.B ubuntu\-bug \-p
.I packagename

.B ubuntu\-bug \-P
.I PID

.SH DESCRIPTION

.B ubuntu\-bug 
is a command-line interface for filing bugs in Ubuntu.

To report a bug against a particular package, use the
.B \-p
option with the binary package name, e. g.

.RS 4
.nf
ubuntu\-bug \-p firefox
.fi
.RE

In order to add more information to the bug report that could
help the developers to fix the problem, you can also specify a process
ID instead of (or in addition to) a package name:

.RS 4
.nf
$ pidof gnome-terminal
5139
$ ubuntu-bug -P 5139
.fi
.RE

.B ubuntu\-bug
detects whether KDE or Gnome is running and calls
.B apport\-gtk
or 
.B apport\-qt
accordingly. If neither is available, or the session does not run
under X11, it calls
.B apport\-cli
for a command-line client.

.SH AUTHOR
.B apport
and the accompanying tools are developed by Martin Pitt
<martin.pitt@ubuntu.com>.
