.TH ubuntu\-bug 1 "February 15, 2007" "Martin Pitt"

.SH NAME

ubuntu\-bug \- file a bug against an Ubuntu package

.SH SYNOPSIS

.B ubuntu\-bug
.I packagename

.B ubuntu\-bug
.I /path/to/program

.B ubuntu\-bug 
.I PID

.B ubuntu\-bug 
.I /var/crash/_my_program.crash

.SH DESCRIPTION

.B ubuntu\-bug 
is a command-line interface for filing bugs in Ubuntu.

To report a bug against a particular binary package, supply it as an argument:

.RS 4
.nf
ubuntu\-bug firefox
.fi
.RE

You can also supply a path to a program instead of a package name for the same result:

.RS 4
.nf
ubuntu\-bug /usr/bin/gnome-screensaver
.fi
.RE

In order to add more information to the bug report that could
help the developers to fix the problem, you can also specify a process
ID instead of (or in addition to) a package name:

.RS 4
.nf
$ pidof gnome-terminal
5139
$ ubuntu-bug 5139
.fi
.RE

As a special case, to report a bug against the Linux kernel, you do not need to
use the full package name (such as linux-image-2.6.28-4-generic); you can just use

.RS 4
.nf
ubuntu\-bug linux
.fi
.RE

to report a bug against the currently running kernel.

Finally, you can use ubuntu\-bug to report a crash report:

.RS 4
.nf
ubuntu\-bug /var/crash/_bin_bash.1000.crash
.fi
.RE

.B ubuntu\-bug
detects whether KDE or Gnome is running and calls
.B apport\-gtk
or 
.B apport\-qt
accordingly. If neither is available, or the session does not run
under X11, it calls
.B apport\-cli
for a command-line client.

.SH AUTHOR
.B apport
and the accompanying tools are developed by Martin Pitt
<martin.pitt@ubuntu.com>.
