#!/usr/bin/python

# Collect information about a crash and create a report in the directory
# specified by apport_utils.report_dir.
# See https://wiki.ubuntu.com/AutomatedProblemReports for details.
#
# Copyright (c) 2006 Canonical Ltd.
# Author: Martin Pitt <martin.pitt@ubuntu.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See http://www.gnu.org/copyleft/gpl.html for
# the full text of the license.

import sys, os, os.path, subprocess, time, traceback
import tempfile, glob, apt

import problem_report

sys.path.append(os.path.abspath(os.path.dirname(sys.argv[0])))
import apport_utils

#################################################################
#
# functions
#
#################################################################

def _read_file(f):
    '''Try to read given file and return its contents, or return a textual
    error if it failed.'''

    try:
	return open(f).read().strip()
    except IOError, e:
	error_log('_read_file %s: %s' % (f, str(e)))
	return 'Error: ' + str(e)

def _command_output(command, input = None, stderr = subprocess.STDOUT):
    '''Try to execute given command (array) and return its stdout, or return
    a textual error if it failed.'''

    try:
	sp = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=stderr, close_fds=True)
    except OSError, e:
	error_log('_command_output Popen(%s): %s' % (str(command), str(e)))
	return 'Error: ' + str(e)

    out = sp.communicate(input)[0]
    if sp.returncode == 0:
	return out
    else:
	error_log('_command_output %s failed with exit code %i: %s' % (
	    str(command), sp.returncode, out))
	return 'Error: command %s failed with exit code %i: %s' % (
	    str(command), sp.returncode, out)

def drop_privileges(pid):
    '''Change user and group to match the given target process.'''

    stat = None
    try:
	stat = os.stat('/proc/' + pid)
    except OSError:
	raise ValueError, 'Invalid process ID'

    os.setgid(stat.st_gid)
    os.setuid(stat.st_uid)
    assert os.getuid() == stat.st_uid

def init_error_log():
    '''Open a suitable error log if sys.stderr is not a tty.'''

    if not os.isatty(sys.stderr.fileno()):
	try:
	    f = open('/var/log/apport.log', 'a')
	except IOError: # on a permission error, don't touch stderr
	    return
	os.dup2(f.fileno(), sys.stderr.fileno())
	os.dup2(f.fileno(), sys.stdout.fileno())
	f.close()

def error_log(msg):
    '''Output something to the error log.'''

    print >> sys.stderr, 'apport (pid %s) %s:' % (os.getpid(),
	time.asctime()), msg

def transitive_dependencies(package, depends_set, cache):
    '''Recursively add dependencies of package to depends_set, using the given
    apt cache.'''

    try:
	cur_ver = cache[package]._pkg.CurrentVer
    except (AttributeError, KeyError):
	return
    for p in cur_ver.DependsList.get('Depends', []) + cur_ver.DependsList.get('PreDepends', []):
	name = p[0].TargetPkg.Name
	if not name in depends_set:
	    depends_set.add(name)
	    transitive_dependencies(name, depends_set, cache)

#################################################################
#
# classes
#
#################################################################

class InformationCollector:
    '''Collect and store information about the crash.
    
    Fields with acquired data:
    - Signal: signal that caused the crash
    - ExecutablePath: path to the crashed executable
    - Stacktrace: stack trace
    - ThreadStacktrace: thread apply all bt full
    - Package: package name and version; not present if info['ExecutablePath'] does
      not belong to a package
    - SourcePackage: source package name
    - Dependencies: names and versions of depending packages; not present if
      Package is not present
    - ProcCmdline: /proc/<pid>/cmdline
    - ProcEnviron: /proc/<pid>/environ
    - ProcStatus: /proc/<pid>/status
    - ProcMaps: /proc/<pid>/maps
    - DistroRelease: lsb_release -sir
    - Uname: uname -a

    TODO: StackFrame
    '''

    def __init__(self, pid, signum, coredump = None):
	'''Initialize object, but do not collect information yet.'''

	self.info = problem_report.ProblemReport('Crash')
	self.info['Signal'] = signum
	self.pid = pid
	if coredump:
	    self.info['CoreDump'] = (coredump,)
	self.unlink_coredump = False

	# determine program name
	self.info['ExecutablePath'] = os.readlink('/proc/' + pid + '/exe')

    def collect_runtime_information(self):
	'''Collect information about the process runtime (mainly from /proc).

	This requires that the target process still exists and needs root
	privileges.'''

	self._get_proc()

    def collect_static_information(self):
	'''Collect information about the process' environment and other static
	data.

	The process does not need to exist any more, and no special privileges
	are required.'''

	self._get_pkg()
	self._get_os()
	self._get_gdb()

    def __del__(self):
	if self.unlink_coredump:
	    os.unlink(self.info['CoreDump'][0])

    def _get_proc(self):
	'''Collect information from /proc.'''

	self.info['ProcEnviron'] = _read_file('/proc/'+ self.pid + '/environ'). \
	    replace('\n', '\\n').replace('\0', '\n').strip()
	self.info['ProcStatus'] = _read_file('/proc/' + self.pid + '/status')
	self.info['ProcCmdline'] = _read_file('/proc/' + self.pid + '/cmdline').rstrip('\0')
	self.info['ProcMaps'] = _read_file('/proc/' + self.pid + '/maps')

    def _get_pkg(self):
	'''Check whether executable belongs to a package and determine its
	name, version, and the versions of its dependencies.'''

	# get dpkg -s <package> output
	out = _command_output(['dpkg', '-S', self.info['ExecutablePath']])
	if out.startswith('Error:'):
	    return 
	pkg = out.split(':', 1)[0]

	cache = apt.Cache()

	self.info['Package'] = '%s %s' % (pkg, cache[pkg].installedVersion)
	self.info['SourcePackage'] = cache[pkg].sourcePackageName

	# get set of all transitive dependencies
	dependencies = set([])
	transitive_dependencies(pkg, dependencies, cache)

	# get dependency versions
	self.info['Dependencies'] = ''
	for dep in dependencies:
	    try:
		cur_ver = cache[dep]._pkg.CurrentVer
	    except (KeyError, AttributeError):
		continue
	    if self.info['Dependencies']:
		self.info['Dependencies'] += '\n'
	    self.info['Dependencies'] += '%s %s' % (dep, cur_ver.VerStr)

    def _get_os(self):
	'''Collect information about system.'''

	self.info['DistroRelease'] = _command_output(['lsb_release', '-sir']).strip().replace('\n', ' ')
	self.info['Uname'] = _command_output(['uname', '-a']).strip()

    def _get_gdb(self):
	'''Get information from gdb.
	
	This only works if we have a core dump. We cannot generate a core dump
	on our own if we are called by the kernel, since the target process is
	in uninterruptible kernel sleep.'''

	if not self.info.has_key('CoreDump'):
	    return
	core = self.info['CoreDump'][0]

	self.info['Stacktrace'] = _command_output(['gdb', '--batch', '--ex',
	    'bt full', self.info['ExecutablePath'], core],
	    stderr=open('/dev/null')).replace('\n\n', '\n.\n').strip()
	self.info['ThreadStacktrace'] = _command_output(['gdb', '--batch', '--ex',
	    'thread apply all bt full', self.info['ExecutablePath'], core],
	    stderr=open('/dev/null')).replace('\n\n', '\n.\n').strip()

	self._copy_shrink_corefile()

    def _copy_shrink_corefile(self):
	'''Copy the core file and redue its size.
	
	The original core dump will be removed by the kernel once the
	kernel-invoked apport instance exits.'''

	if not self.info.has_key('CoreDump'):
	    return

	shrinkcorefile = tempfile.NamedTemporaryFile()
	shrinkcorefile.close()
	if subprocess.call(['objcopy', self.info['CoreDump'][0], shrinkcorefile.name],
	    stderr=subprocess.PIPE) == 0 \
	    and os.path.exists(shrinkcorefile.name):
	    self.info['CoreDump'] = (shrinkcorefile.name,)
	    self.unlink_coredump = True

#################################################################
#
# main
#
#################################################################

init_error_log()

if len(sys.argv) < 3 or len(sys.argv) > 4:
    print >> sys.stderr, 'Usage:', sys.argv[0], '<pid> <signal number> [<path to core dump>]'
    sys.exit(-1)


pid = sys.argv[1]
signum = sys.argv[2]

# try to find the core dump file
if len(sys.argv) == 4:
    coredump = sys.argv[3]
else:
    coredump = None

# if path is relative, prepend cwd of crashed process
if coredump and len(coredump) > 0 and coredump[0] != '/':
    coredump = os.path.join(os.readlink('/proc/' + pid + '/cwd'), coredump)

if coredump and not os.path.exists(coredump):
    coredump = None

error_log('called with: ' + str(sys.argv) + ', using core file ' + str(coredump))

try:
    pidstat = os.stat('/proc/' + pid)
except OSError:
    error_log('Invalid PID')
    sys.exit(1)

exename = os.readlink('/proc/' + pid + '/exe')

# ignore non-package binaries
if subprocess.call(['fgrep', '-qx', exename] + glob.glob('/var/lib/dpkg/info/*.list')) != 0:
    error_log('executable does not belong to a package, ignoring')
    sys.exit(0)

# Create crash report file descriptor. We prefer to create the report in
# report_dir if we can create a file there; if not, we just use stderr.
try:
    report = '%s/%s.%i.crash' % (apport_utils.report_dir, exename.replace('/', '_'), pidstat.st_uid)
    if os.path.exists(report) and not apport_utils.seen_report(report):
	error_log('apport: report %s already exists and unseen, doing nothing to avoid disk usage DoS' % report)
	sys.exit(1)
    reportfile = open(report, 'w')
    os.chmod(report, 0600)
    os.chown(report, pidstat.st_uid, pidstat.st_gid)
except (OSError, IOError):
    reportfile = sys.stderr

try:
    ic = InformationCollector(pid, signum, coredump)

    # reading /proc after drop_privileges() (when called from the kernel)
    # does not work, so do this with original privileges.
    ic.collect_runtime_information()
    drop_privileges(pid)
    ic.collect_static_information()

    ic.info.write(reportfile)
    if reportfile != sys.stderr:
	error_log('wrote report %s for package %s' % (report, ic.info['Package']))
except SystemExit:
    raise
except Exception, e:
    error_log('Unhandled exception:')
    traceback.print_exc()
    print >> sys.stderr, 'pid: %i, uid: %i, gid: %i, euid: %i, egid: %i' % (
       os.getpid(), os.getuid(), os.getgid(), os.geteuid(), os.getegid())
