#!/usr/bin/python

# Collect information about a crash and create a report in /var/crash/.
# See https://wiki.ubuntu.com/AutomatedProblemReports for details.
#
# Copyright (c) 2006 Canonical Ltd.
# Author: Martin Pitt <martin.pitt@ubuntu.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See http://www.gnu.org/copyleft/pgl.html for
# the full text of the license.

import sys, os, subprocess


#################################################################
#
# functions
#
#################################################################

def _read_file(f):
    '''Try to read given file and return its contents, or return a textual
    error if it failed.'''

    try:
	return open(f).read()
    except IOError, e:
	return 'Error: ' + str(e)

def _command_output(command, input = None):
    '''Try to execute given command (array) and return its stdout, or return
    a textual error if it failed.'''

    try:
	sp = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    except OSError, e:
	return 'Error: ' + str(e)

    out = sp.communicate(input)[0]
    if sp.returncode == 0:
	return out
    else:
	return 'Error: command %s failed with exit code %i: %s' % (str(command), sp.returncode, out)

def write_debcontrol(file, fields):
    '''Write dictionary 'fields' into the given file-like object, using Debian
    control file format.'''

    for k, v in fields.iteritems():
	if v.find('\n') >= 0:
	    print >> file, k + ':'
	    print >> file, '', v.replace('\n', '\n ')
	else:
	    print >> file, k + ':', v

#################################################################
#
# classes
#
#################################################################

class InformationCollector:
    '''Collect and store information about the crash.
    
    Fields with acquired data:
    - signal: signal that caused the crash
    - executable: path to the crashed executable
    - stacktrace: stack trace
    - environment: env variables from /proc/<pid>/environ
    - pkg: package name and version; not present if info['executable'] does not
      belong to a package
    - dependencies: names and versions of depending packages; not present if
      pkg is not present
    - procstatus: /proc/<pid>/status
    - lsb_release: lsb_release -sir
    - uname: uname -a
    '''

    def __init__(self, pid, signal):
	'Collects all information and stores them in the appropriate fields.'

	self.info = {}
	self.info['signal'] = signal
	self.pid = pid

	# determine program name
	try:
	    self.info['executable'] = os.readlink('/proc/' + pid + '/exe')
	except OSError:
	    pass # ignore it, there's nothing we can do about it

	self._get_proc()
	self._get_pkg()
	self._get_os()

    def _get_proc(self):
	'''Collect information from /proc.'''

	self.info['environment'] = _read_file('/proc/'+ self.pid + '/environ'). \
	    replace('\n', '\\n').replace('\0', '\n')
	self.info['procstatus'] = _read_file('/proc/' + self.pid + '/status')

    def _get_pkg(self):
	'''Check whether executable belongs to a package and determine its
	name, version, and the versions of its dependencies.'''

	pass

    def _get_os(self):
	'''Collect information about system.'''

	self.info['lsb_release'] = _command_output(['lsb_release', '-sir']).strip().replace('\n', ' ')
	self.info['uname'] = _command_output(['uname', '-a']).strip()

#################################################################
#
# main
#
#################################################################

if len(sys.argv) != 3:
    print 'Usage:', sys.argv[0], '<pid> <signal number>'
    sys.exit(-1)

ic = InformationCollector(sys.argv[1], sys.argv[2])

write_debcontrol(sys.stdout, ic.info)
