#!/bin/sh -ex
CRASHDUMP=/proc/sys/kernel/crashdump-helper
[ -e $CRASHDUMP ] || CRASHDUMP=/proc/sys/kernel/crashdump
python problem_report.py -v
python apport/fileutils.py -v
python apport/report.py -v
if [ -e $CRASHDUMP ] && [ -n "`cat $CRASHDUMP`" ]; then
    ./test-apport kernel
else
    PYTHONPATH=. ./test-apport lib
fi
