#!/usr/bin/python

import apport
import apport.fileutils

def test_kernel_crashreport(reportfile):
    report = apport.Report()
    report.load(open(reportfile))
    preport.add_kernel_crash_info()


if __name__ == "__main__":
    test_kernel_crashreport("/var/crash/linux-image-2.6.30-9-generic.0.crash")
    
