#!/bin/sh -e
if [ -e /proc/sys/kernel/crashdump ]; then
    echo $(readlink -f $(dirname $0)/apport) > /proc/sys/kernel/crashdump
else
    echo $(readlink -f $(dirname $0)/apport) > /proc/sys/kernel/crashdump-helper
fi
