#!/bin/sh
RELEASE="$1"
TARBALL="$2"
MIRROR="$3"
APTSOURCES="$4"

[ "$RELEASE" ] && [ "$TARBALL" ] && [ "$MIRROR" ] || {
    echo "Usage: $0 <release> <tarball> <mirror> [<additional apt sources>]"
    exit 1
}

# make absolute path
TARBALL=`readlink -f "$TARBALL"`

D=`mktemp -d`
trap "cd /; rm -rf $D" 0 1 2 3 4 5 6 7 8 10 11 12 13 14 15

fakechroot -s fakeroot debootstrap --variant=fakechroot "$RELEASE" "$D" "$MIRROR"

# fix symlinks
cd "$D"
find -type l | while read f; do 
    target=`readlink $f`
    newtarget=${target#$D}
    if [ "$target" != "$newtarget" ]; then
        rm $f
        ln -s "$newtarget" "$f"
    fi
done

# create symlink to mirror dir for file:// mirrors
mirror_dir="${MIRROR#file://}"
if [ "$mirror_dir" != "$MIRROR" ]; then
    mkdir -p .`dirname "$mirror_dir"`
    ln -s "$mirror_dir" ."${mirror_dir%/}"
fi

# set up default apt sources
echo "deb $MIRROR $RELEASE main\n$APTSOURCES" > "$D/etc/apt/sources.list"

fakechroot -s fakeroot chroot "$D" apt-get update

# clean up cruft
rm -f var/cache/apt/archives/partial/* 2>/dev/null
rm -f var/cache/apt/archives/* 2>/dev/null
rm -rf tmp/* 2>/dev/null

echo "Building $TARBALL..."
tar cp . | gzip -9 > "$TARBALL"
