usr/share/apport/apport
usr/share/apport/apport-checkreports
usr/share/apport/package_hook
usr/share/apport/kernel_hook
usr/share/apport/gcc_ice_hook
usr/share/apport/apport-unpack usr/bin
usr/share/apport/testsuite/
usr/share/doc/apport
usr/share/locale
usr/share/icons
usr/share/mime
usr/share/apport/package-hooks
usr/share/apport/general-hooks
usr/share/apport/*cli* usr/bin/
../local/ubuntu-bug usr/bin
