#!/bin/sh -e

# clean up old *.pyc stuff from broken previous versions so that the programs
# actually use the new library in the python path
if dpkg --compare-versions "$2" le-nl 0.33; then
    for i in apport_utils.pyc apport_utils.pyo problem_report.pyc problem_report.pyo; do
        rm -f /usr/lib/python2.4/site-packages/$i /usr/lib/python2.5/site-packages/$i
    done
    rm -rf /usr/lib/python2.4/site-packages/apport /usr/lib/python2.5/site-packages/apport
fi

#DEBHELPER#
