#!/usr/bin/python3
#
# Collect information about a package installation/upgrade failure.
#
# Copyright (c) 2007 - 2009 Canonical Ltd.
# Author: Martin Pitt <martin.pitt@ubuntu.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See http://www.gnu.org/copyleft/gpl.html for
# the full text of the license.

import argparse
import os
import sys

import apport
import apport.fileutils


def mkattrname(path):
    """Convert a file path to a problem report attribute name."""

    name = ""
    for directory in path.split(os.sep):
        if not directory:
            continue
        name += "".join(
            [c for c in directory[0].upper() + directory[1:] if c.isalnum()]
        )
    return name


def parse_args():
    """Parse command line options and return arguments."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-p",
        "--package",
        required=True,
        help="Specify the package name which failed to upgrade (mandatory)",
    )
    parser.add_argument(
        "-l",
        "--log",
        action="append",
        dest="logs",
        help="Append given log file, or, if it is a directory,"
        " all files in it (can be specified multiple times)",
    )
    parser.add_argument(
        "-t",
        "--tags",
        help="Add the following tags to the bug report (comma separated)",
    )
    return parser.parse_args()


#
# main
#

# parse command line arguments
options = parse_args()

# create report
pr = apport.Report("Package")
pr.add_package(options.package)
pr["SourcePackage"] = apport.packaging.get_source(options.package)
pr["ErrorMessage"] = (sys.stdin, False)

if options.tags:
    tags = options.tags.replace(",", "")
    pr["Tags"] = tags

for line in options.logs or []:
    if os.path.isfile(line):
        pr[mkattrname(line)] = (line,)
    elif os.path.isdir(line):
        for f in os.listdir(line):
            path = os.path.join(line, f)
            if os.path.isfile(path):
                pr[mkattrname(path)] = (path,)

# write report
try:
    with apport.fileutils.make_report_file(pr) as f:
        pr.write(f)
except OSError as error:
    apport.fatal("Cannot create report: " + str(error))
